// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentPIN():Promise<string>;

export function GetLocalIPs():Promise<Array<string>>;

export function StartServer(arg1:number):Promise<void>;
