// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentPIN() {
  return window['go']['main']['App']['GetCurrentPIN']();
}

export function GetLocalIPs() {
  return window['go']['main']['App']['GetLocalIPs']();
}

export function RegisterWithDevice(arg1, arg2) {
  return window['go']['main']['App']['RegisterWithDevice'](arg1, arg2);
}

export function SendTestFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendTestFile'](arg1, arg2, arg3);
}

export function ShowDeviceRegistered(arg1) {
  return window['go']['main']['App']['ShowDeviceRegistered'](arg1);
}

export function ShowFileReceived(arg1) {
  return window['go']['main']['App']['ShowFileReceived'](arg1);
}

export function StartServer(arg1) {
  return window['go']['main']['App']['StartServer'](arg1);
}
