// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentPIN():Promise<string>;

export function GetLocalIPs():Promise<Array<string>>;

export function RegisterWithDevice(arg1:string,arg2:number):Promise<void>;

export function SendTestFile(arg1:string,arg2:number,arg3:string):Promise<void>;

export function ShowDeviceRegistered(arg1:string):Promise<void>;

export function ShowFileReceived(arg1:string):Promise<void>;

export function StartServer(arg1:number):Promise<void>;
